name: AMR_prediction
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - r-base=4.1.3
  - r-tidyverse==2.0.0
  - r-ggpubr==0.6.0
  - r-logger==0.2.2
  - r-xgboost
  - r-vroom
  - r-janitor
  - genometester4
  - numpy
  - pandas
  - r-DiagrammeR
  - r-Ckmeans.1d.dp